version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: api
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U docker']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      target: development
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: test
      DATABASE_URL: postgresql://docker:docker@postgres:5432/api?schema=public
    command: ['npm', 'run', 'test:e2e']
