apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: production
spec:
  type: ClusterIP  # Pode ser ClusterIP, já que o Ingress vai expor
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 3000


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: production
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: geraldobl58/api:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_URL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: production
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  rules:
  - host: api.ogeraldoluiz.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 80
  tls:
  - hosts:
    - api.ogeraldoluiz.com
    secretName: tls-cert-api-production
---
# Secret com a string de conexão do Postgres
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: development
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL2RvYWRtaW46c2hvdy1wYXNzd29yZEBkYi1wb3N0Z3Jlc3FsLWZyYTEtOTQ5NTItZG8tdXNlci0yMTgxNDUzNS0wLmQuZGIub25kaWdpdGFsb2NlYW4uY29tOjI1MDYwL2RlZmF1bHRkYj9zc2xtb2RlPXJlcXVpcmU=

---
apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  namespace: development
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: geraldobl58/api:latest
          command: ["npx", "prisma", "migrate", "deploy"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_URL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi
      restartPolicy: Never