apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  namespace: production
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: geraldobl58/api:v{{GITHUB_RUN_NUMBER}}
          command: ["npx", "prisma", "migrate", "deploy"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-env-secret
                  key: DATABASE_URL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi
      restartPolicy: Never
